#:include kv/firstscreen.kv
#:include kv/secondscreen.kv
#:include kv/thirdscreen.kv


GridLayout:
    cols: 1
    ScreenManager:
        id:screen_manager
        FirstScreen:
            name: "first_screen"
            id:first_screen
        SecondScreen:
            name: "second_screen"
            id: second_screen
        ThirdScreen:
            name: "third_screen"
            id: third_screen
